title: Events Carousel
status: 'wip'
preview: '@preview'
context:
  events:
    - date: '10 September 1960'
      title: '<h3>Righteous indignation</h3>'
      description: '<p>On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment.</p>'
      gallery: '@atomic-gallery.gallery'
    - date: '20 May 1970'
      title: 'Nam libero tempore'
      description: '<p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.</p>'
      gallery: '@atomic-gallery.gallery'
    - date: '30 September 2000'
      title: 'Lorem ipsum dolor sit amet'
      description: '<p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>'
      gallery: '@atomic-gallery.gallery'
    - date: 'now'
      title: 'koa Sünd Edlweiss'
      description: '<p>Hoid auf der Oim, da gibt’s koa Sünd Edlweiss, Haberertanz. Ned woar luja mim allerweil oba hi Leonhardifahrt! I bin a woschechta Bayer i daad scheans nomoi moand oans.</p>'
      gallery: '@atomic-gallery.gallery'
    - date: '+2 months'
      title: 'Freibia Engelgwand'
      description: '<p>Almrausch owe griaß God beinand, jedza abfieseln wo hi griasd eich midnand Broadwurschtbudn Freibia Engelgwand fensdaln! Woibbadinga schnacksln resch Jodler, mechad wos.</p>'
      gallery: '@atomic-gallery.gallery'
